### ISSUE TITLE
Repo is unreachable (error 113)

### ISSUE THREAD

**Issue by joshcangit** [ethanhs/apt.cli.rs#10]
Repository now has another new error.
`xhs HEAD apt.0xe.me`
```
xhs: error: error sending request for url (https://apt.0xe.me/): error trying to connect: tcp connect error: Host is unreachable (os error 113)

Caused by:
    0: error trying to connect: tcp connect error: Host is unreachable (os error 113)
    1: tcp connect error: Host is unreachable (os error 113)
    2: Host is unreachable (os error 113)

```

**Comment by ethanhs** [comment]
The main server hosting this seems to have experienced a kernel panic, I should be able to bring it back up after work later today. Sorry for the trouble!

**Comment by joshcangit** [comment]
Ok, just noticed it's back online now.

**Comment by joshcangit** [comment]
The error is back on again.

**Comment by ethanhs** [comment]
Hi, sorry a server update went awry, I am hoping to get things back up soon.

**Comment by ethanhs** [comment]
New ETA for returning to service is Thursday. I got a bad motherboard and the system is locking up, so I will need to put back the old motherboard. Sorry for any issues!

**Comment by ethanhs** [comment]
The repo is back up, sorry for the delay! Getting the server working again was more difficult than anticipated. Thank you all for your patience. I'll be updating the repo with the latest release of bat tonight.
