### ISSUE TITLE
Repo down

### ISSUE THREAD

**Issue by timkgh** [ethanhs/apt.cli.rs#12]
Is this project still maintained?

**Comment by ethanhs** [comment]
Hm, I think there was a brief outage on 9/24 but my monitoring has not alerted me about any outage, and the site seems up on my end. I am still regularly updating the apt repo.

Perhaps the site being behind cloudflare presents an issue?

**Comment by timkgh** [comment]
These links
https://apt.cli.rs/pool
https://apt.cli.rs/dists
redirect to
https://apt.cli.rs:8080/pool/
https://apt.cli.rs:8080/dists/
Which fail.

**Comment by ethanhs** [comment]
Sorry for the delay, been a bit under the weather, but the repo should be back up. I will add probes for the pool and dists endpoints, thanks for reporting the issue!

**Comment by timkgh** [comment]
Are you sure you fixed it? It still doesn't work for me.

**Comment by ethanhs** [comment]
Ugh, it worked for me briefly but then stopped working, I'll dig into it and figure out why it is redirecting wrong.

**Comment by ethanhs** [comment]
Oh, I see.  https://apt.cli.rs/pool redirects incorrectly,  https://apt.cli.rs/pool/ works.

**Comment by ethanhs** [comment]
I fixed the links on the main site. apt shouldn't care about this because it never accesses the bare directory.

**Comment by ethanhs** [comment]
I should have closed this.
