### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by ulrichSchreiner** [ethanhs/apt.cli.rs#18]
The certificate expired

~~~
$ LANG=C date -u
Tue Oct 22 15:14:49 UTC 2024
~~~

But the server responds with an expire date of Oct 17:

~~~
$ curl -kv https://apt.cli.rs
...
* Server certificate:
*  subject: CN=apt.cli.rs
*  start date: Jul 19 01:49:45 2024 GMT
*  expire date: Oct 17 01:49:44 2024 GMT
*  issuer: C=US; O=Let's Encrypt; CN=E5
~~~

**Comment by tangopium** [comment]
This issue is urgent as the tool cannot be installed anymore due to the invalid SSL certificate

**Comment by j-lakeman** [comment]
friendly nudge @ethanhs

**Comment by ZimaBlueee** [comment]
+1

**Comment by roib20** [comment]
This mirror still works for me: https://apt.0xe.me

**Comment by ethanhs** [comment]
Sorry all, had some health issues and had to move suddenly, so my life's been all over the past two weeks. I've restored access and fixed the broken SSL cert issue.
