### ISSUE TITLE
package support for aarch64

### ISSUE THREAD

**Issue by ow0x** [ethanhs/apt.cli.rs#3]
Hi,

I found this repo through xh tool's github page. I also added the repo on my Ubuntu 20.04 system through instructions provided in readme. However I noticed that apt was unable to locate package xh. After a lot of forehead scratching and searching for error on internet, I found that my system architecture is aarch64 which is not listed in dists/contents of this repo.

It would be really beneficial for me if you guys can add support for aarch64 for all the useful packages listed on this repo.

**Comment by ethanhs** [comment]
Hi! I only upload what the upstream package provides, so I think you will have to request that from upstream xh. It looks like they recently added aarch64 musl linked binaries https://github.com/ducaale/xh/issues/212, so perhaps you can ask for deb packages as well :)

**Comment by ow0x** [comment]
ok thanks!
