### ISSUE TITLE
Repo stopped working

### ISSUE THREAD

**Issue by Arzaroth** [ethanhs/apt.cli.rs#4]
Hello there,

As per the title, the repo is inaccessible.  I get the following message :
~~~
Cannot initiate the connection to apt.0xe.me:443 (2602:fe10:ff4::140). - connect (101: Network is unreachable) Could not connect to apt.0xe.me:443 (23.165.224.140). - connect (113: No route to host)
~~~

If you're having hosting problems, I'm sure some of us here (me included) have the means to host it somewhere.

**Comment by ethanhs** [comment]
Hi! I actually moved my server today to a new location, it should be down for another hour at most, but if you still run into issues, please follow up!

**Comment by joshcangit** [comment]
I've just tested it with `curl`.
Confirmed the host is unreachable.

> `curl -ISs https://apt.cli.rs/`
```
curl: (7) Failed to connect to apt.cli.rs port 443 after 4242 ms: No route to host
```

**Comment by joshcangit** [comment]
It seems the website coming back online but not well.
I get some **Error 1001** page when visiting it.

> curl -ISs https://apt.cli.rs/
```
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

> wget -nv --spider https://apt.cli.rs/
```
OpenSSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
Unable to establish SSL connection.
```

But I get **Error 409** if I test using the "http" address.

> curl -ISs http://apt.cli.rs/
```
HTTP/1.1 409 Conflict
Date: Fri, 06 May 2022 03:17:45 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 16
Connection: close
X-Frame-Options: SAMEORIGIN
Referrer-Policy: same-origin
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Server: cloudflare
CF-RAY: 706e908d1ddc470f-SIN
```

> wget -nv --spider http://apt.cli.rs/
```
http://apt.cli.rs/:
Remote file does not exist -- broken link!!!
```

**Comment by ethanhs** [comment]
Should be back up, sorry for the delay.

Let me know if you run into any errors.

**Comment by joshcangit** [comment]
Ok, it works now. Thanks.

> curl -ISs https://apt.cli.rs/
```
HTTP/2 200 
server: nginx/1.18.0 (Ubuntu)
date: Fri, 06 May 2022 05:02:51 GMT
content-type: text/html
content-length: 2339
last-modified: Sun, 17 Oct 2021 18:26:11 GMT
etag: "616c6ac3-923"
accept-ranges: bytes
```

> wget -nv --spider https://apt.cli.rs/
```
2022-05-06 13:03:06 URL: https://apt.cli.rs/ 200 OK
```

**Comment by ethanhs** [comment]
Glad to hear it. Sorry again for the downtime, it shouldn't happen again (I've had 3 9s with other sites before this :/)
