### ISSUE TITLE
Repo stopped working again

### ISSUE THREAD

**Issue by joshcangit** [ethanhs/apt.cli.rs#5]
I'm now getting a new error with the web address.
This is the line from doing `sudo apt update`.
```
W: Failed to fetch https://apt.0xe.me/dists/all/InRelease  Could not connect to apt.0xe.me:443 (23.135.200.43), connection timed out
```

**Comment by ethanhs** [comment]
Seems to be working for me, maybe intermittent failure on your end? Let me know if it persists and I'll dig into it.
